/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kwantec.unoflip;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author rodrigo
 */
public class UnoFlipGUI extends javax.swing.JPanel{

    /**
     * Creates new form UnoFlipGUI
     */
    public UnoFlipGUI() {
        initComponents();
        Mano mano= new Mano(this.PanelMano);
        Turno turno = new Turno(this.PanelCartaCentral);
        Stack stack = mano.getSevenStack(new Stack(),turno);
        turno.setCarta(stack.get(0));
        System.out.println(4);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCartaCentral = new javax.swing.JPanel();
        PanelMano = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout());

        PanelCartaCentral.setLayout(new java.awt.GridLayout());
        add(PanelCartaCentral);

        PanelMano.setLayout(new java.awt.GridLayout(4, 0));
        add(PanelMano);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelCartaCentral;
    private javax.swing.JPanel PanelMano;
    // End of variables declaration//GEN-END:variables

    
}
